### ISSUE TITLE
`conda-env-activate` does not run activate.d scripts

### ISSUE THREAD

**Issue by danielkrizian** [necaris/conda.el#25]
`M-x conda-env-activate` does seem to ignore contents of the conda environment's [activate.d](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#macos-and-linux) directory

For example, my `q_activate.sh` script  sets the QHOME environment variable and the test outside emacs works correctly:
```
$ echo $QHOME         # empty

$ conda activate q

(q) $ cat $CONDA_PREFIX/etc/conda/activate.d/q_activate.sh
#!/bin/bash 
export OLD_QHOME="$QHOME"
export QHOME="${CONDA_PREFIX}/q"

(q) $ echo $QHOME          # set as expected
/opt/conda/envs/q/q
```

In emacs and with `conda.el`, when I activate the q environment, the QHOME env variable is empty:
```
M-x conda-env-activate
HELM Conda Env Activate -> Choose a conda environment: -> q
M-: (getenv "QHOME")
""
```
Albeit, PATH environment variable seems to be modified correctly by the activation:
```
M-: (getenv "PATH")
"/opt/conda/envs/q/bin:/opt/conda/bin:/opt/conda/condabin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games" 
```

**Expected Behavior**
All scripts in `$CONDA_PREFIX/etc/conda/activate.d` and `$CONDA_PREFIX/etc/conda/deactivate.d` directories should be run, as per the [conda docs](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html?highlight=activate.d#saving-environment-variables).

**Comment by necaris** [comment]
@danielkrizian sorry for the delayed response, for some reason I haven't been seeing notifications for new issues. What would you like to see happen here -- more generally than just your specific use case? Since as you point out `activate.d` can contain arbitrary scripts, I'm not sure how we should run them and load any changed environment variables, settings, etc into Emacs!

**Comment by danielkrizian** [comment]
In general use case, could `conda-env-activate` command also execute all `*.sh` scripts located in the `activate.d` directory of the selected conda environment? In any shell, running `$ conda activate [selectedCondaEnvName]` does it, `conda.el` currently does not.

**Comment by necaris** [comment]
@danielkrizian I'm still not clear on why you're asking for those scripts to be run, so I can't be sure if any of the possible solutions I'm thinking of will help you.

When you activate a conda environment in a _shell_, running all of the `activate.d` scripts updates the state of the shell -- which may be more than just environment variables. Will just updating the environment variables solve your problem? If so that's something I can look into.

**Comment by randomphrase** [comment]
Hi, I would also like to see this support. I have just started at a new team which is using conda, and it is all new to me so please excuse any terminology problems.

My team uses conda to install the `gxx_linux-64` package which is the C++ compiler. On activation this runs the corresponding script. The main (if not only) purpose of this script is to set a bunch of environment variables which are used by the compiler, such as `CC` and `CXX` which point to the compiler itself, and also other environment variables which set compiler flags, linker flags, and more. These environment variables are needed when I build my project. The makefile uses `$CXX` to find the compiler and so it will fail if this isn't set. Right now when I use M-x `compile` it fails because this environment is not set.

In answer to your question I *think* that updating the environment variables will solve the problem (speaking for myself, not the OP).

For what it's worth, my workaround right now is to source the activation scripts prior to invoking the build tool when I use M-x `compile`. So for example, instead of using `make -C {dir} {target}` I use `for s in $VIRTUAL_ENV/etc/conda/activation.d/*.sh ; do source $s ; done ; make -C {dir} {target}`.

**Comment by necaris** [comment]
It seems like environment variables are the main use case for this, so 
I think I've got a path forward. I'm not going to get to this soon, 
unfortunately -- would appreciate any help, though! I'll try to have a 
look this weekend.

**Comment by necaris** [comment]
Just adding a note that #53 was another vote for environment variable support.

**Comment by iskur** [comment]
Here is another vote in favor of environment variable support.
The problem I described in SciTools/cartopy#1725 also appears because of a script (`proj4-activate.sh`) which sets a new environment variable is not run on `conda-env-activate`.

**Comment by necaris** [comment]
I believe as of https://github.com/necaris/conda.el/commit/44df826ce92831c2f3b446778275194a51d388e7 this is solved using upstream functionality in `conda` itself. So I'm closing this, but if it's not actually fixed please reopen!

**Comment by artelse** [comment]
I have a `activate.d` script to set an env variable, but `conda.el` does not pick it up. Would love to know how I can add env variables on activating conda. (Running latest conda.el)
