### ISSUE TITLE
No conda environment for file 

### ISSUE THREAD

**Issue by notuntoward** [necaris/conda.el#8]
Every time I visit any file, I get a message like this:

  No conda environment for file <c:/Users/scotto/OneDrive/scotto/ANY_FILE>

Would it be possible to print this message only when I've visited a python file?

**Comment by necaris** [comment]
@notuntoward the latest version should fix this -- you now have two options to silence the above message.
  1. if you _never_ want to see it, you can now set the custom variable `conda-message-on-environment-switch` to `nil`, and it will silence the messages about switching to an environment (or not finding one)
  2. if you only want `conda` functionality on Python buffers, instead of using `conda-env-autoactivate-mode`, you might try using `conda-env-activate-for-buffer` as a hook function for `python-mode`, so it would only be run when you were working in a `python-mode` file. Adding the following code to your init file should do the trick:
     ```elisp
     (add-hook 'python-mode-hook 'conda-env-activate-for-buffer)
     ```

**Comment by notuntoward** [comment]
Perfect.  Thanks.
